// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuiFLn_xY6t_rQnWOyn1qjO8Ekq7QXw7k',
    appId: '1:375947638109:web:c22c798d0c329e0e7524b4',
    messagingSenderId: '375947638109',
    projectId: 'collegeproject-5d4bf',
    authDomain: 'collegeproject-5d4bf.firebaseapp.com',
    storageBucket: 'collegeproject-5d4bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlC5F0ftcj8wXk61NQNo0rwGYsDVf9WRM',
    appId: '1:375947638109:android:92ecd71dffe8ca487524b4',
    messagingSenderId: '375947638109',
    projectId: 'collegeproject-5d4bf',
    storageBucket: 'collegeproject-5d4bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2DlENfhxhDF5qu3ConYVN4AeBjRzSlOg',
    appId: '1:375947638109:ios:e1de4befd105067c7524b4',
    messagingSenderId: '375947638109',
    projectId: 'collegeproject-5d4bf',
    storageBucket: 'collegeproject-5d4bf.appspot.com',
    iosClientId: '375947638109-j5m11fjh867aogcj381t9m09cntktr0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeproject',
  );
}
